# Main purpose is to test whether on other system the Library builds the CLI

name: MSBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  BUILD_ARCHITECTURE: x64

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Pull repo
      uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build OPLibrary
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}\OPLibrary.sln
      
    #- name: Make dist dir
    #  working-directory: ${{env.GITHUB_WORKSPACE}}
    #  run: mkdir ${{env.SOLUTION_FILE_PATH}}/dist
      
    #- name: Zip build output
    #  working-directory: ${{env.GITHUB_WORKSPACE}}
    #  run: Compress-Archive ${{env.SOLUTION_FILE_PATH}}/x64/${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}/dist/build.zip 
        
    # zips the output
    - name: Upload build output
      uses: actions/upload-artifact@v3
      with:
        name: OPLibrary
        path: ${{env.SOLUTION_FILE_PATH}}/${{env.BUILD_ARCHITECTURE}}/${{env.BUILD_CONFIGURATION}}
        retention-days: 14
