# Main purpose is to test whether on other system the Library builds the CLI

name: MSBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  BUILD_ARCHITECTURE: x64

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Pull repo
      uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
    
    - name: Install Doxygen with Choco
      run: choco install doxygen.install

    - name: Build OPLibrary
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}\OPLibrary.sln
        
    # zips the output
    - name: Upload build output
      uses: actions/upload-artifact@v3
      with:
        name: OPLibrary
        path: ${{env.SOLUTION_FILE_PATH}}/${{env.BUILD_ARCHITECTURE}}/${{env.BUILD_CONFIGURATION}}
        retention-days: 7
        
    - name: Generate docs
      run: |
        & "C:/Program Files/doxygen/bin/doxygen.exe" .\Doxyfile
        
    # zip and upload docs
    - name: Zip and upload docs
      uses: actions/upload-artifact@v3
      with:
        name: OPLibrary Docs
        path: ${{env.SOLUTION_FILE_PATH}}/Documentation
        retention-days: 7
